version: '3.9'
services:
  db:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./DocumentAnalysis.API
    container_name: DocumentAnalysis.API
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__Mongo=mongodb://db:27017
    depends_on:
      - db

  documentanalysis-ui:
    build:
      context: ./DocumentAnalysis.UI
    container_name: DocumentAnalysis.UI
    ports:
      - "5173:5173"
    volumes:
      - ./DocumentAnalysis.UI:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures hot reload works in Docker
    depends_on:
      - backend

volumes:
  mongo_data: